version: "3.9"

services:
  sidecar:
    image: ameron/sidecar:1.0.0
    environment:
      - APP_NAME=ameron-sidecar
      - APP_MODEL_HTTP_URL=http://model:8000/predict
      - APP_MODEL_BACKEND=logger
    ports:
    - "8080:8080"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper