version: "3.9"

services:
  sidecar:
    image: ameron/sidecar:0.0.1
    environment:
      - APP_NAME=ameron-sidecar
      - APP_MODEL_BACKEND=http
      - APP_MODEL_HTTP_URL=http://localhost:8000/predict
      - APP_PREDICTION_EVENT_CONSUMER=kafka
      - APP_PROVIDER_KAFKA_BROKERS=localhost
    network_mode: host

  kafka:
    image: wurstmeister/kafka
    network_mode: host
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host