version: "3.9"

services:
  kafka:
    image: wurstmeister/kafka
    network_mode: host
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host